---
Name: toastblocks
---

Page:
  extensions:
    - Toast\Blocks\Extensions\PageExtension

Toast\Blocks\Extensions\PageExtension:
  available_blocks:
    - Toast\Blocks\TextBlock

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    # - blocks/css/blocks.css

SilverStripe\Assets\File:
  extensions:
    - Toast\Blocks\Extensions\FileExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    CmsActionsExtension: Toast\Blocks\Extensions\CmsActionsExtension

Toast\Blocks\TextBlock:
  icon: 'blocks/images/text.svg'

Toast\Blocks\AccordionBlock:
  icon: 'blocks/images/accordion.svg'

Toast\Blocks\ChildLinkBlock:
  icon: 'blocks/images/link.svg'
  content_field: 'Content'

Toast\Blocks\ColumnBlock:
  icon: 'blocks/images/splitblock.svg'

Toast\Blocks\DownloadBlock:
  icon: 'blocks/images/download.svg'

Toast\Blocks\GalleryBlock:
  icon: 'blocks/images/gallery.svg'

Toast\Blocks\HeroBlock:
  icon: 'blocks/images/hero.svg'

Toast\Blocks\ImageBlock:
  icon: 'blocks/images/image.svg'

Toast\Blocks\LinkBlock:
  icon: 'blocks/images/link.svg'

Toast\Blocks\NewsBlock:
  icon: 'blocks/images/news.svg'

Toast\Blocks\PercentageBlock:
  icon: 'blocks/images/.svg'

Toast\Blocks\TabbedContentBlock:
  icon: 'blocks/images/statistic.svg'

Toast\Blocks\TestimonialBlock:
  icon: 'blocks/images/testimonial.svg'

Toast\Blocks\VideoBlock:
  icon: 'blocks/images/video.svg'

Toast\Blocks\SplitBlock:
  icon: 'blocks/images/splitblock.svg'
