---
Name: toastblocks
---

Page:
  extensions:
    - Toast\Blocks\Extensions\PageExtension

Toast\Blocks\Extensions\PageExtension:
  available_blocks:
    - Toast\Blocks\TextBlock

SilverStripe\Assets\File:
  extensions:
    - Toast\Blocks\Extensions\FileExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    CmsActionsExtension: Toast\Blocks\Extensions\CmsActionsExtension

Toast\Blocks\TextBlock:
  icon: '[resources]/images/text.svg'

Toast\Blocks\AccordionBlock:
  icon: '[resources]/images/accordion.svg'

Toast\Blocks\ChildLinkBlock:
  icon: '[resources]/images/link.svg'
  content_field: 'Content'

Toast\Blocks\ColumnBlock:
  icon: '[resources]/images/splitblock.svg'

Toast\Blocks\DownloadBlock:
  icon: '[resources]/images/download.svg'

Toast\Blocks\GalleryBlock:
  icon: '[resources]/images/gallery.svg'

Toast\Blocks\HeroBlock:
  icon: '[resources]/images/hero.svg'

Toast\Blocks\ImageBlock:
  icon: '[resources]/images/image.svg'

Toast\Blocks\InstagramBlock:
  icon: '[resources]/images/social.svg'

Toast\Blocks\LinkBlock:
  icon: '[resources]/images/link.svg'

Toast\Blocks\NewsBlock:
  icon: '[resources]/images/news.svg'

Toast\Blocks\PercentageBlock:
  icon: '[resources]/images/percentage.svg'

Toast\Blocks\TabbedContentBlock:
  icon: '[resources]/images/tabbedcontent.svg'

Toast\Blocks\TestimonialBlock:
  icon: '[resources]/images/testimonial.svg'

Toast\Blocks\VideoBlock:
  icon: '[resources]/images/video.svg'

Toast\Blocks\SplitBlock:
  icon: '[resources]/images/splitblock.svg'

