---
Name: toastblocks
---
Page:
  extensions:
    - Toast\Blocks\Extensions\PageExtension

Toast\Blocks\Extensions\PageExtension:
  available_blocks:
    - Toast\Blocks\TextBlock

SilverStripe\Assets\File:
  extensions:
    - Toast\Blocks\Extensions\FileExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    CmsActionsExtension: Toast\Blocks\Extensions\CmsActionsExtension

Toast\Blocks\TextBlock:
  icon: "[resources]/images/text-alt.svg"

Toast\Blocks\AccordionBlock:
  icon: "[resources]/images/accordion.svg"

Toast\Blocks\ChildLinkBlock:
  icon: "[resources]/images/link.svg"
  content_field: "Content"

Toast\Blocks\DownloadBlock:
  icon: "[resources]/images/download.svg"

Toast\Blocks\ImageBlock:
  icon: "[resources]/images/image.svg"

Toast\Blocks\LinkBlock:
  icon: "[resources]/images/link.svg"

Toast\Blocks\TabbedContentBlock:
  icon: "[resources]/images/statistic.svg"

Toast\Blocks\VideoBlock:
  icon: "[resources]/images/video.svg"

Toast\Blocks\ImageTextBlock:
  icon: "[resources]/images/imagetext.svg"

Toast\Blocks\UserFormBlock:
  icon: "[resources]/images/form.svg"
